repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.31.0
    hooks:
      - id: eslint
        name: eslint
        entry: eslint --fix
        language: node
        pass_filenames: true
        types_or: [vue, ts, tsx, javascript]
        additional_dependencies:
          - eslint
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          - eslint-plugin-vue
          - '@vue/eslint-config-typescript'
        stages: [pre-commit]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.2.5
  #   hooks:
  #     - id: prettier
  #       additional_dependencies: ['prettier', 'prettier-plugin-vue']

  # - repo: https://github.com/pre-commit/mirrors-stylelint
  #   rev: v15.11.0
  #   hooks:
  #     - id: stylelint
  #       additional_dependencies: ['stylelint', 'stylelint-config-standard', 'stylelint-config-recommended-vue']
