repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: system
        files: \.(vue|ts|tsx|js)$
        types: [file]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.2.5
  #   hooks:
  #     - id: prettier
  #       additional_dependencies: ['prettier', 'prettier-plugin-vue']

  # - repo: https://github.com/pre-commit/mirrors-stylelint
  #   rev: v15.11.0
  #   hooks:
  #     - id: stylelint
  #       additional_dependencies: ['stylelint', 'stylelint-config-standard', 'stylelint-config-recommended-vue']
